source("settings.R")
source("R/utils.R")
source("R/ReadingData.R")
source("R/augmentData.R")
source("R/Missingness.R")
source("R/Q1.R")
#lapply(rev(list.files("R/", pattern = "\\.R$", full.names = TRUE, recursive = TRUE)), source)